apiVersion: apps/v1
kind: Deployment
metadata:
  name:  voxelab-aries-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:  voxelab-aries-exporter
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  voxelab-aries-exporter
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  voxelab-aries-exporter
        image:  voxelab-aries-exporter
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 15m
            memory: 30Mi
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: env-config
        ports:
        - containerPort:  9000
          name: metrics
      restartPolicy: Always