apiVersion: v1
kind: Service
metadata:
  name: voxelab-aries-exporter
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: voxelab-aries-exporter
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: metrics
    protocol: TCP
    port: 9000
    targetPort: 9000
